# @generated by flavor/fedora44/import_snapshot.py -- do not edit by hand; re-run the generator.
# Everything package-specific lives in packages.json; buck2 load()s that
# file directly, exposing the parsed document as the symbol `value`. So
# this stub stays the same size no matter how large the snapshot grows.
load("@antlir//antlir/antlir2/package_managers/dnf/rules:snapshot.bzl", "rpm_snapshot")
load(":packages.json", snapshot = "value")

oncall("antlir")

rpm_snapshot(snapshot = snapshot)
