load("//antlir/bzl:build_defs.bzl", "export_file")
load(":suite.bzl", "suite")

oncall("antlir")

export_file(
    name = "dummy_signing_key",
    src = "keys/dummy.secret.pgp",
)

suite(
    name = "trixie",
    architectures = [
        "amd64",
        "arm64",
    ],
    archive_url = "https://mirror.facebook.net/debian",
    components = [
        "main",
        "contrib",
    ],
    visibility = ["PUBLIC"],
)
